name: call_recorder_vtx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^9.0.0
  wakelock_plus: ^1.2.5
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  just_audio: ^0.9.36
  audio_session: ^0.1.21
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
